import { NextRequest, NextResponse } from 'next/server'
import { getSupabaseAdmin } from '@/lib/supabase/server'

export const dynamic = 'force-dynamic'

// All 100 products organized in 5 batches
const allProducts = [
  // BATCH 1: Fruits & Vegetables (20 products)
  [
    { name: 'Organic Bananas', slug: 'organic-bananas', short_description: 'Sweet and ripe organic bananas', description: 'Naturally ripened organic bananas, perfect for snacking or smoothies. Rich in potassium and fiber.', price_pence: 129, compare_at_price_pence: 159, stock_quantity: 150, unit: 'bunch', is_organic: true, is_vegan: true, is_vegetarian: true, image_url: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=400&h=400&fit=crop' },
    { name: 'Royal Gala Apples 6 Pack', slug: 'royal-gala-apples-6', short_description: 'Crisp and sweet British apples', description: 'Hand-picked Royal Gala apples from British orchards. Perfect for lunchboxes and snacking.', price_pence: 199, stock_quantity: 120, unit: 'pack', is_vegan: true, is_vegetarian: true, image_url: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=400&h=400&fit=crop' },
    { name: 'Fresh Strawberries 400g', slug: 'fresh-strawberries-400g', short_description: 'Sweet British strawberries', description: 'Juicy, hand-picked strawberries. Perfect for desserts, smoothies or eating fresh.', price_pence: 299, compare_at_price_pence: 349, stock_quantity: 80, unit: 'pack', is_vegan: true, is_vegetarian: true, image_url: 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=400&h=400&fit=crop' },
    { name: 'Seedless Red Grapes 500g', slug: 'seedless-red-grapes-500g', short_description: 'Sweet seedless grapes', description: 'Plump, sweet seedless red grapes. Great for snacking and fruit salads.', price_pence: 249, stock_quantity: 90, unit: 'pack', is_vegan: true, is_vegetarian: true, image_url: 'https://images.unsplash.com/photo-1537640538966-79f369143f8f?w=400&h=400&fit=crop' },
    { name: 'Ripe Avocados 2 Pack', slug: 'ripe-avocados-2-pack', short_description: 'Ready to eat avocados', description: 'Perfectly ripe Hass avocados, ready to eat. Great for guacamole, toast or salads.', price_pence: 179, stock_quantity: 100, unit: 'pack', is_vegan: true, is_vegetarian: true, image_url: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=400&h=400&fit=crop' },
    { name: 'Organic Carrots 1kg', slug: 'organic-carrots-1kg', short_description: 'Fresh organic carrots', description: 'Crunchy organic carrots, perfect for roasting, soups or eating raw with hummus.', price_pence: 149, stock_quantity: 130, unit: 'bag', is_organic: true, is_vegan: true, is_vegetarian: true, image_url: 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=400&h=400&fit=crop' },
    { name: 'Vine Tomatoes 500g', slug: 'vine-tomatoes-500g', short_description: 'Ripe tomatoes on the vine', description: 'Sun-ripened tomatoes on the vine. Perfect for salads, sandwiches and cooking.', price_pence: 179, stock_quantity: 110, unit: 'pack', is_vegan: true, is_vegetarian: true, image_url: 'https://images.unsplash.com/photo-1546470427-e26264be0b11?w=400&h=400&fit=crop' },
    { name: 'Baby Spinach 200g', slug: 'baby-spinach-200g', short_description: 'Fresh baby spinach leaves', description: 'Tender baby spinach leaves, washed and ready to eat. Great for salads and smoothies.', price_pence: 159, stock_quantity: 85, unit: 'bag', is_vegan: true, is_vegetarian: true, image_url: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400&h=400&fit=crop' },
    { name: 'Cucumber', slug: 'cucumber', short_description: 'Fresh whole cucumber', description: 'Crisp, refreshing cucumber. Perfect for salads, sandwiches and tzatziki.', price_pence: 69, stock_quantity: 140, unit: 'each', is_vegan: true, is_vegetarian: true, image_url: 'https://images.unsplash.com/photo-1449300079323-02e209d9d3a6?w=400&h=400&fit=crop' },
    { name: 'Red Onions 1kg', slug: 'red-onions-1kg', short_description: 'Mild red onions', description: 'Sweet and mild red onions, perfect for salads, grilling and caramelizing.', price_pence: 119, stock_quantity: 120, unit: 'bag', is_vegan: true, is_vegetarian: true, image_url: 'https://images.unsplash.com/photo-1518977956812-cd3dbadaaf31?w=400&h=400&fit=crop' },
    { name: 'Garlic Bulbs 4 Pack', slug: 'garlic-bulbs-4-pack', short_description: 'Fresh garlic bulbs', description: 'Aromatic garlic bulbs, essential for any kitchen. Adds depth to any dish.', price_pence: 99, stock_quantity: 150, unit: 'pack', is_vegan: true, is_vegetarian: true, image_url: 'https://images.unsplash.com/photo-1540148426945-6cf22a6b2383?w=400&h=400&fit=crop' },
    { name: 'Iceberg Lettuce', slug: 'iceberg-lettuce', short_description: 'Crisp iceberg lettuce', description: 'Fresh, crispy iceberg lettuce. Perfect base for salads and burgers.', price_pence: 79, stock_quantity: 95, unit: 'each', is_vegan: true, is_vegetarian: true, image_url: 'https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?w=400&h=400&fit=crop' },
    { name: 'Chestnut Mushrooms 250g', slug: 'chestnut-mushrooms-250g', short_description: 'Earthy chestnut mushrooms', description: 'Flavorful chestnut mushrooms with a firm texture. Great for stir-fries and pasta.', price_pence: 139, stock_quantity: 100, unit: 'pack', is_vegan: true, is_vegetarian: true, image_url: 'https://images.unsplash.com/photo-1504545102780-26774c1bb073?w=400&h=400&fit=crop' },
    { name: 'Sweet Corn 4 Pack', slug: 'sweet-corn-4-pack', short_description: 'Fresh corn on the cob', description: 'Sweet and tender corn on the cob. Perfect for BBQs and summer meals.', price_pence: 199, stock_quantity: 70, unit: 'pack', is_vegan: true, is_vegetarian: true, image_url: 'https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=400&h=400&fit=crop' },
    { name: 'Mixed Bell Peppers 3 Pack', slug: 'mixed-bell-peppers-3-pack', short_description: 'Colourful bell peppers', description: 'Red, yellow and green bell peppers. Great for stir-fries, salads and stuffing.', price_pence: 169, stock_quantity: 90, unit: 'pack', is_vegan: true, is_vegetarian: true, image_url: 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=400&h=400&fit=crop' },
    { name: 'Lemons 5 Pack', slug: 'lemons-5-pack', short_description: 'Zesty fresh lemons', description: 'Juicy lemons, perfect for cooking, drinks and dressings.', price_pence: 129, stock_quantity: 110, unit: 'pack', is_vegan: true, is_vegetarian: true, image_url: 'https://images.unsplash.com/photo-1582087463261-ddea03f80f5d?w=400&h=400&fit=crop' },
    { name: 'Fresh Blueberries 150g', slug: 'fresh-blueberries-150g', short_description: 'Plump fresh blueberries', description: 'Antioxidant-rich blueberries. Perfect for breakfast, baking and snacking.', price_pence: 249, stock_quantity: 75, unit: 'pack', is_vegan: true, is_vegetarian: true, image_url: 'https://images.unsplash.com/photo-1498557850523-fd3d118b962e?w=400&h=400&fit=crop' },
    { name: 'Mango', slug: 'mango', short_description: 'Sweet ripe mango', description: 'Perfectly ripe mango with sweet, tropical flavour. Ready to eat.', price_pence: 119, stock_quantity: 85, unit: 'each', is_vegan: true, is_vegetarian: true, image_url: 'https://images.unsplash.com/photo-1553279768-865429fa0078?w=400&h=400&fit=crop' },
    { name: 'Tenderstem Broccoli 200g', slug: 'tenderstem-broccoli-200g', short_description: 'Premium tenderstem broccoli', description: 'Delicate tenderstem broccoli with a sweet, mild flavour. Quick to cook.', price_pence: 199, stock_quantity: 80, unit: 'pack', is_vegan: true, is_vegetarian: true, image_url: 'https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?w=400&h=400&fit=crop' },
    { name: 'Fresh Pineapple', slug: 'fresh-pineapple', short_description: 'Sweet whole pineapple', description: 'Tropical pineapple, sweet and juicy. Great for fruit salads and smoothies.', price_pence: 149, stock_quantity: 60, unit: 'each', is_vegan: true, is_vegetarian: true, image_url: 'https://images.unsplash.com/photo-1550258987-190a2d41a8ba?w=400&h=400&fit=crop' },
  ],

  // BATCH 2: Dairy, Eggs & Bakery (20 products)
  [
    { name: 'Semi-Skimmed Milk 2L', slug: 'semi-skimmed-milk-2l', short_description: 'Fresh British milk', description: 'Fresh British semi-skimmed milk from local farms. Perfect for everyday use.', price_pence: 145, stock_quantity: 200, unit: 'bottle', is_vegetarian: true, image_url: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?w=400&h=400&fit=crop' },
    { name: 'Organic Whole Milk 1L', slug: 'organic-whole-milk-1l', short_description: 'Creamy organic milk', description: 'Rich, creamy organic whole milk from grass-fed cows.', price_pence: 175, stock_quantity: 120, unit: 'bottle', is_organic: true, is_vegetarian: true, image_url: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?w=400&h=400&fit=crop' },
    { name: 'Salted Butter 250g', slug: 'salted-butter-250g', short_description: 'British salted butter', description: 'Rich, creamy British butter. Perfect for cooking and spreading.', price_pence: 249, stock_quantity: 150, unit: 'pack', is_vegetarian: true, image_url: 'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=400&h=400&fit=crop' },
    { name: 'Greek Style Yogurt 500g', slug: 'greek-style-yogurt-500g', short_description: 'Thick creamy yogurt', description: 'Rich and creamy Greek style yogurt. Great with fruit, honey or in cooking.', price_pence: 199, stock_quantity: 100, unit: 'pot', is_vegetarian: true, image_url: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400&h=400&fit=crop' },
    { name: 'Mature Cheddar 350g', slug: 'mature-cheddar-350g', short_description: 'Sharp mature cheddar', description: 'Rich, tangy mature cheddar cheese. Perfect for sandwiches and cooking.', price_pence: 349, stock_quantity: 90, unit: 'block', is_vegetarian: true, image_url: 'https://images.unsplash.com/photo-1618164436241-4473940d1f5c?w=400&h=400&fit=crop' },
    { name: 'Mozzarella Ball 125g', slug: 'mozzarella-ball-125g', short_description: 'Fresh mozzarella', description: 'Soft, milky fresh mozzarella. Perfect for pizza, salads and caprese.', price_pence: 159, stock_quantity: 85, unit: 'pack', is_vegetarian: true, image_url: 'https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=400&h=400&fit=crop' },
    { name: 'Double Cream 300ml', slug: 'double-cream-300ml', short_description: 'Rich double cream', description: 'Thick, rich double cream. Perfect for desserts and sauces.', price_pence: 179, stock_quantity: 80, unit: 'pot', is_vegetarian: true, image_url: 'https://images.unsplash.com/photo-1559598467-f8b76c8155d0?w=400&h=400&fit=crop' },
    { name: 'Free Range Large Eggs 6', slug: 'free-range-large-eggs-6', short_description: 'British free range eggs', description: 'Large free range eggs from happy British hens.', price_pence: 199, stock_quantity: 140, unit: 'box', is_vegetarian: true, image_url: 'https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=400&h=400&fit=crop' },
    { name: 'Organic Eggs 6 Pack', slug: 'organic-eggs-6-pack', short_description: 'Organic free range eggs', description: 'Organic eggs from free range hens fed on organic feed.', price_pence: 279, stock_quantity: 100, unit: 'box', is_organic: true, is_vegetarian: true, image_url: 'https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=400&h=400&fit=crop' },
    { name: 'Parmesan Wedge 150g', slug: 'parmesan-wedge-150g', short_description: 'Italian Parmesan cheese', description: 'Authentic Italian Parmigiano-Reggiano. Aged for rich, nutty flavour.', price_pence: 399, stock_quantity: 60, unit: 'wedge', is_vegetarian: true, image_url: 'https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=400&h=400&fit=crop' },
    { name: 'White Bread Loaf 800g', slug: 'white-bread-loaf-800g', short_description: 'Soft white bread', description: 'Soft, fluffy white bread. Perfect for sandwiches and toast.', price_pence: 119, stock_quantity: 120, unit: 'loaf', is_vegan: true, is_vegetarian: true, image_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=400&fit=crop' },
    { name: 'Wholemeal Bread 800g', slug: 'wholemeal-bread-800g', short_description: 'Nutritious wholemeal bread', description: 'Hearty wholemeal bread, high in fibre. Great for healthy sandwiches.', price_pence: 139, stock_quantity: 100, unit: 'loaf', is_vegan: true, is_vegetarian: true, image_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=400&fit=crop' },
    { name: 'Croissants 4 Pack', slug: 'croissants-4-pack', short_description: 'Buttery French croissants', description: 'Light, flaky butter croissants. Perfect for breakfast.', price_pence: 199, stock_quantity: 80, unit: 'pack', is_vegetarian: true, image_url: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=400&h=400&fit=crop' },
    { name: 'Seeded Batch Loaf', slug: 'seeded-batch-loaf', short_description: 'Artisan seeded bread', description: 'Crusty artisan bread topped with mixed seeds. Great with soup.', price_pence: 179, stock_quantity: 70, unit: 'loaf', is_vegan: true, is_vegetarian: true, image_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=400&fit=crop' },
    { name: 'Pain au Chocolat 4 Pack', slug: 'pain-au-chocolat-4-pack', short_description: 'Chocolate filled pastries', description: 'Buttery pastries filled with rich dark chocolate. A breakfast treat.', price_pence: 229, stock_quantity: 75, unit: 'pack', is_vegetarian: true, image_url: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=400&h=400&fit=crop' },
    { name: 'Bagels 5 Pack', slug: 'bagels-5-pack', short_description: 'Fresh plain bagels', description: 'Chewy, authentic bagels. Perfect for breakfast or lunch.', price_pence: 159, stock_quantity: 90, unit: 'pack', is_vegan: true, is_vegetarian: true, image_url: 'https://images.unsplash.com/photo-1585535936432-734a9cff5fdb?w=400&h=400&fit=crop' },
    { name: 'Brioche Buns 4 Pack', slug: 'brioche-buns-4-pack', short_description: 'Sweet brioche burger buns', description: 'Soft, buttery brioche buns. Elevate your burgers and sandwiches.', price_pence: 169, stock_quantity: 85, unit: 'pack', is_vegetarian: true, image_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=400&fit=crop' },
    { name: 'Sourdough Boule', slug: 'sourdough-boule', short_description: 'Artisan sourdough bread', description: 'Traditional sourdough with a crispy crust and tangy flavour.', price_pence: 299, stock_quantity: 50, unit: 'loaf', is_vegan: true, is_vegetarian: true, image_url: 'https://images.unsplash.com/photo-1585478259715-876acc5be8fc?w=400&h=400&fit=crop' },
    { name: 'Feta Cheese 200g', slug: 'feta-cheese-200g', short_description: 'Greek feta cheese', description: 'Authentic Greek feta, crumbly and tangy. Perfect for salads.', price_pence: 229, stock_quantity: 80, unit: 'pack', is_vegetarian: true, image_url: 'https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=400&h=400&fit=crop' },
    { name: 'Brie 200g', slug: 'brie-200g', short_description: 'Creamy French Brie', description: 'Soft, creamy French Brie cheese. Perfect for cheese boards.', price_pence: 299, stock_quantity: 65, unit: 'wheel', is_vegetarian: true, image_url: 'https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=400&h=400&fit=crop' },
  ],

  // BATCH 3: Meat & Fish (20 products)
  [
    { name: 'Chicken Thighs 1kg', slug: 'chicken-thighs-1kg', short_description: 'Juicy chicken thighs', description: 'Succulent chicken thighs, perfect for roasting or grilling.', price_pence: 499, stock_quantity: 80, unit: 'pack', image_url: 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=400&h=400&fit=crop' },
    { name: 'Chicken Wings 1kg', slug: 'chicken-wings-1kg', short_description: 'Perfect for BBQ', description: 'Meaty chicken wings, ideal for BBQ, buffalo wings or Asian dishes.', price_pence: 399, stock_quantity: 70, unit: 'pack', image_url: 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=400&h=400&fit=crop' },
    { name: 'Beef Mince 500g', slug: 'beef-mince-500g', short_description: 'Lean beef mince', description: 'Quality lean beef mince, perfect for bolognese, burgers and more.', price_pence: 449, stock_quantity: 90, unit: 'pack', image_url: 'https://images.unsplash.com/photo-1603048297172-c92544798d5a?w=400&h=400&fit=crop' },
    { name: 'Ribeye Steak 250g', slug: 'ribeye-steak-250g', short_description: 'Premium ribeye steak', description: 'Marbled ribeye steak with exceptional flavour. Restaurant quality.', price_pence: 799, compare_at_price_pence: 899, stock_quantity: 45, unit: 'each', is_featured: true, image_url: 'https://images.unsplash.com/photo-1600891964092-4316c288032e?w=400&h=400&fit=crop' },
    { name: 'Sirloin Steak 225g', slug: 'sirloin-steak-225g', short_description: 'Classic sirloin steak', description: 'Tender sirloin steak, perfect for a special dinner.', price_pence: 699, stock_quantity: 50, unit: 'each', image_url: 'https://images.unsplash.com/photo-1600891964092-4316c288032e?w=400&h=400&fit=crop' },
    { name: 'Pork Sausages 6 Pack', slug: 'pork-sausages-6-pack', short_description: 'Traditional pork sausages', description: 'Classic British pork sausages, perfect for fry-ups and bangers & mash.', price_pence: 329, stock_quantity: 100, unit: 'pack', image_url: 'https://images.unsplash.com/photo-1601628828688-632f38a5a7d0?w=400&h=400&fit=crop' },
    { name: 'Smoked Back Bacon 250g', slug: 'smoked-back-bacon-250g', short_description: 'British smoked bacon', description: 'Quality smoked back bacon, perfect for the full English.', price_pence: 349, stock_quantity: 95, unit: 'pack', image_url: 'https://images.unsplash.com/photo-1606851091851-e8c8c0fca5ba?w=400&h=400&fit=crop' },
    { name: 'Lamb Mince 500g', slug: 'lamb-mince-500g', short_description: 'British lamb mince', description: 'Flavourful lamb mince, perfect for shepherds pie and kofta.', price_pence: 549, stock_quantity: 60, unit: 'pack', image_url: 'https://images.unsplash.com/photo-1603048297172-c92544798d5a?w=400&h=400&fit=crop' },
    { name: 'Pork Chops 4 Pack', slug: 'pork-chops-4-pack', short_description: 'Thick cut pork chops', description: 'Meaty pork chops, great for grilling or pan-frying.', price_pence: 499, stock_quantity: 70, unit: 'pack', image_url: 'https://images.unsplash.com/photo-1432139555190-58524dae6a55?w=400&h=400&fit=crop' },
    { name: 'Turkey Breast Mince 500g', slug: 'turkey-breast-mince-500g', short_description: 'Lean turkey mince', description: 'Extra lean turkey breast mince. A healthier alternative for any mince dish.', price_pence: 449, stock_quantity: 65, unit: 'pack', image_url: 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=400&h=400&fit=crop' },
    { name: 'Fresh Cod Fillets 280g', slug: 'fresh-cod-fillets-280g', short_description: 'Flaky white cod', description: 'Fresh Atlantic cod fillets, perfect for fish and chips or baking.', price_pence: 549, stock_quantity: 55, unit: 'pack', image_url: 'https://images.unsplash.com/photo-1510130387422-82bed34b37e9?w=400&h=400&fit=crop' },
    { name: 'Haddock Fillets 280g', slug: 'haddock-fillets-280g', short_description: 'Fresh haddock fillets', description: 'Sweet, delicate haddock fillets. Great for fish pie and kedgeree.', price_pence: 579, stock_quantity: 50, unit: 'pack', image_url: 'https://images.unsplash.com/photo-1510130387422-82bed34b37e9?w=400&h=400&fit=crop' },
    { name: 'King Prawns 200g', slug: 'king-prawns-200g', short_description: 'Jumbo king prawns', description: 'Large, succulent king prawns. Perfect for stir-fries and curries.', price_pence: 499, stock_quantity: 60, unit: 'pack', image_url: 'https://images.unsplash.com/photo-1510130387422-82bed34b37e9?w=400&h=400&fit=crop' },
    { name: 'Smoked Salmon 120g', slug: 'smoked-salmon-120g', short_description: 'Scottish smoked salmon', description: 'Premium Scottish smoked salmon. Perfect for bagels and canapés.', price_pence: 449, stock_quantity: 70, unit: 'pack', image_url: 'https://images.unsplash.com/photo-1499125562588-29fb8a56b5d5?w=400&h=400&fit=crop' },
    { name: 'Sea Bass Fillets 260g', slug: 'sea-bass-fillets-260g', short_description: 'Delicate sea bass', description: 'Tender sea bass fillets with a mild, sweet flavour.', price_pence: 649, stock_quantity: 40, unit: 'pack', image_url: 'https://images.unsplash.com/photo-1510130387422-82bed34b37e9?w=400&h=400&fit=crop' },
    { name: 'Beef Burgers 4 Pack', slug: 'beef-burgers-4-pack', short_description: 'Premium beef burgers', description: 'Handmade beef burgers with the perfect meat to fat ratio.', price_pence: 399, stock_quantity: 85, unit: 'pack', image_url: 'https://images.unsplash.com/photo-1603048297172-c92544798d5a?w=400&h=400&fit=crop' },
    { name: 'Chicken Drumsticks 1kg', slug: 'chicken-drumsticks-1kg', short_description: 'Meaty drumsticks', description: 'Juicy chicken drumsticks, perfect for BBQ and oven roasting.', price_pence: 349, stock_quantity: 75, unit: 'pack', image_url: 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=400&h=400&fit=crop' },
    { name: 'Whole Chicken 1.5kg', slug: 'whole-chicken-1-5kg', short_description: 'Free range whole chicken', description: 'Free range whole chicken, perfect for Sunday roast.', price_pence: 699, stock_quantity: 50, unit: 'each', image_url: 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=400&h=400&fit=crop' },
    { name: 'Tuna Steaks 250g', slug: 'tuna-steaks-250g', short_description: 'Fresh tuna steaks', description: 'Sashimi-grade tuna steaks, best served rare.', price_pence: 699, stock_quantity: 35, unit: 'pack', image_url: 'https://images.unsplash.com/photo-1510130387422-82bed34b37e9?w=400&h=400&fit=crop' },
    { name: 'Diced Beef 500g', slug: 'diced-beef-500g', short_description: 'Braising steak diced', description: 'Quality diced beef for stews, casseroles and pies.', price_pence: 549, stock_quantity: 65, unit: 'pack', image_url: 'https://images.unsplash.com/photo-1603048297172-c92544798d5a?w=400&h=400&fit=crop' },
  ],

  // BATCH 4: Pantry & Beverages (20 products)
  [
    { name: 'Basmati Rice 1kg', slug: 'basmati-rice-1kg', short_description: 'Premium basmati rice', description: 'Long grain aromatic basmati rice, perfect with curries.', price_pence: 249, stock_quantity: 150, unit: 'bag', is_vegan: true, is_vegetarian: true, is_gluten_free: true, image_url: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=400&fit=crop' },
    { name: 'Spaghetti 500g', slug: 'spaghetti-500g', short_description: 'Italian spaghetti', description: 'Classic Italian spaghetti, made from durum wheat.', price_pence: 129, stock_quantity: 180, unit: 'pack', is_vegan: true, is_vegetarian: true, image_url: 'https://images.unsplash.com/photo-1551462147-ff29053bfc14?w=400&h=400&fit=crop' },
    { name: 'Penne Pasta 500g', slug: 'penne-pasta-500g', short_description: 'Italian penne rigate', description: 'Ridged penne pasta that holds sauce perfectly.', price_pence: 129, stock_quantity: 160, unit: 'pack', is_vegan: true, is_vegetarian: true, image_url: 'https://images.unsplash.com/photo-1551462147-ff29053bfc14?w=400&h=400&fit=crop' },
    { name: 'Chopped Tomatoes 400g', slug: 'chopped-tomatoes-400g', short_description: 'Italian chopped tomatoes', description: 'Sun-ripened Italian tomatoes, perfect for sauces and stews.', price_pence: 79, stock_quantity: 200, unit: 'tin', is_vegan: true, is_vegetarian: true, is_gluten_free: true, image_url: 'https://images.unsplash.com/photo-1546470427-e26264be0b11?w=400&h=400&fit=crop' },
    { name: 'Extra Virgin Olive Oil 500ml', slug: 'extra-virgin-olive-oil-500ml', short_description: 'Premium olive oil', description: 'Cold-pressed extra virgin olive oil from Mediterranean olives.', price_pence: 449, stock_quantity: 90, unit: 'bottle', is_vegan: true, is_vegetarian: true, is_gluten_free: true, image_url: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400&h=400&fit=crop' },
    { name: 'Baked Beans 415g', slug: 'baked-beans-415g', short_description: 'Classic baked beans', description: 'Haricot beans in rich tomato sauce. A British classic.', price_pence: 89, stock_quantity: 180, unit: 'tin', is_vegan: true, is_vegetarian: true, image_url: 'https://images.unsplash.com/photo-1472476443507-c7a5948772fc?w=400&h=400&fit=crop' },
    { name: 'Organic Porridge Oats 1kg', slug: 'organic-porridge-oats-1kg', short_description: 'Organic Scottish oats', description: 'Wholegrain organic oats, perfect for a healthy breakfast.', price_pence: 249, stock_quantity: 120, unit: 'bag', is_organic: true, is_vegan: true, is_vegetarian: true, image_url: 'https://images.unsplash.com/photo-1614961233913-a5113a4a34ed?w=400&h=400&fit=crop' },
    { name: 'Honey 340g', slug: 'honey-340g', short_description: 'Pure clear honey', description: 'Pure, natural honey. Perfect for sweetening and cooking.', price_pence: 329, stock_quantity: 85, unit: 'jar', is_vegetarian: true, is_gluten_free: true, image_url: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=400&h=400&fit=crop' },
    { name: 'Peanut Butter 340g', slug: 'peanut-butter-340g', short_description: 'Crunchy peanut butter', description: 'No added sugar crunchy peanut butter. High in protein.', price_pence: 279, stock_quantity: 100, unit: 'jar', is_vegan: true, is_vegetarian: true, is_gluten_free: true, image_url: 'https://images.unsplash.com/photo-1536816579748-4ecb3f03d72a?w=400&h=400&fit=crop' },
    { name: 'Tomato Ketchup 460g', slug: 'tomato-ketchup-460g', short_description: 'Classic tomato ketchup', description: 'Rich, tangy tomato ketchup. A kitchen essential.', price_pence: 199, stock_quantity: 140, unit: 'bottle', is_vegan: true, is_vegetarian: true, image_url: 'https://images.unsplash.com/photo-1461009683693-342af2f2d6ce?w=400&h=400&fit=crop' },
    { name: 'Orange Juice 1L', slug: 'orange-juice-1l', short_description: 'Fresh orange juice', description: 'Freshly squeezed orange juice, not from concentrate.', price_pence: 229, stock_quantity: 110, unit: 'carton', is_vegan: true, is_vegetarian: true, is_gluten_free: true, image_url: 'https://images.unsplash.com/photo-1534353473418-4cfa6c56fd38?w=400&h=400&fit=crop' },
    { name: 'Apple Juice 1L', slug: 'apple-juice-1l', short_description: 'Pressed apple juice', description: 'Crisp, refreshing apple juice from British apples.', price_pence: 199, stock_quantity: 100, unit: 'carton', is_vegan: true, is_vegetarian: true, is_gluten_free: true, image_url: 'https://images.unsplash.com/photo-1534353473418-4cfa6c56fd38?w=400&h=400&fit=crop' },
    { name: 'Ground Coffee 227g', slug: 'ground-coffee-227g', short_description: 'Medium roast coffee', description: 'Smooth, balanced medium roast ground coffee.', price_pence: 399, stock_quantity: 90, unit: 'pack', is_vegan: true, is_vegetarian: true, is_gluten_free: true, image_url: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=400&h=400&fit=crop' },
    { name: 'English Breakfast Tea 80 Bags', slug: 'english-breakfast-tea-80', short_description: 'Classic English tea', description: 'Strong, full-bodied English Breakfast tea bags.', price_pence: 299, stock_quantity: 130, unit: 'box', is_vegan: true, is_vegetarian: true, is_gluten_free: true, image_url: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&h=400&fit=crop' },
    { name: 'Sparkling Water 6 Pack', slug: 'sparkling-water-6-pack', short_description: 'Refreshing sparkling water', description: 'Crisp, refreshing sparkling mineral water.', price_pence: 249, stock_quantity: 120, unit: 'pack', is_vegan: true, is_vegetarian: true, is_gluten_free: true, image_url: 'https://images.unsplash.com/photo-1560023907-5f339617ea30?w=400&h=400&fit=crop' },
    { name: 'Coconut Milk 400ml', slug: 'coconut-milk-400ml', short_description: 'Creamy coconut milk', description: 'Rich, creamy coconut milk for curries and desserts.', price_pence: 149, stock_quantity: 95, unit: 'tin', is_vegan: true, is_vegetarian: true, is_gluten_free: true, image_url: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?w=400&h=400&fit=crop' },
    { name: 'Chickpeas 400g', slug: 'chickpeas-400g', short_description: 'Tinned chickpeas', description: 'Ready to eat chickpeas in water. Perfect for hummus and curries.', price_pence: 89, stock_quantity: 150, unit: 'tin', is_vegan: true, is_vegetarian: true, is_gluten_free: true, image_url: 'https://images.unsplash.com/photo-1515543904823-6701e98e4d6e?w=400&h=400&fit=crop' },
    { name: 'Red Kidney Beans 400g', slug: 'red-kidney-beans-400g', short_description: 'Tinned kidney beans', description: 'Rich red kidney beans, perfect for chilli and salads.', price_pence: 79, stock_quantity: 140, unit: 'tin', is_vegan: true, is_vegetarian: true, is_gluten_free: true, image_url: 'https://images.unsplash.com/photo-1515543904823-6701e98e4d6e?w=400&h=400&fit=crop' },
    { name: 'Vegetable Stock Cubes 12', slug: 'vegetable-stock-cubes-12', short_description: 'Rich vegetable stock', description: 'Flavourful vegetable stock cubes for soups and risottos.', price_pence: 129, stock_quantity: 160, unit: 'pack', is_vegan: true, is_vegetarian: true, image_url: 'https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a?w=400&h=400&fit=crop' },
    { name: 'Soy Sauce 150ml', slug: 'soy-sauce-150ml', short_description: 'Dark soy sauce', description: 'Naturally brewed dark soy sauce for Asian cooking.', price_pence: 179, stock_quantity: 110, unit: 'bottle', is_vegan: true, is_vegetarian: true, image_url: 'https://images.unsplash.com/photo-1472476443507-c7a5948772fc?w=400&h=400&fit=crop' },
  ],

  // BATCH 5: Snacks, Frozen & More (20 products)
  [
    { name: 'Milk Chocolate Bar 200g', slug: 'milk-chocolate-bar-200g', short_description: 'Creamy milk chocolate', description: 'Smooth, creamy milk chocolate. Perfect for sharing.', price_pence: 249, stock_quantity: 120, unit: 'bar', is_vegetarian: true, image_url: 'https://images.unsplash.com/photo-1481391319762-47dff72954d9?w=400&h=400&fit=crop' },
    { name: 'Dark Chocolate 70% 100g', slug: 'dark-chocolate-70-100g', short_description: 'Rich dark chocolate', description: 'Intense 70% cocoa dark chocolate for the true connoisseur.', price_pence: 199, stock_quantity: 90, unit: 'bar', is_vegan: true, is_vegetarian: true, image_url: 'https://images.unsplash.com/photo-1481391319762-47dff72954d9?w=400&h=400&fit=crop' },
    { name: 'Salted Crisps 6 Pack', slug: 'salted-crisps-6-pack', short_description: 'Classic salted crisps', description: 'Crunchy, lightly salted potato crisps. A classic snack.', price_pence: 179, stock_quantity: 150, unit: 'multipack', is_vegan: true, is_vegetarian: true, is_gluten_free: true, image_url: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=400&h=400&fit=crop' },
    { name: 'Cheese & Onion Crisps 6 Pack', slug: 'cheese-onion-crisps-6-pack', short_description: 'Tangy cheese & onion', description: 'Classic British cheese and onion flavour crisps.', price_pence: 179, stock_quantity: 140, unit: 'multipack', is_vegetarian: true, is_gluten_free: true, image_url: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=400&h=400&fit=crop' },
    { name: 'Mixed Nuts 200g', slug: 'mixed-nuts-200g', short_description: 'Roasted mixed nuts', description: 'Roasted almonds, cashews, and peanuts. High in protein.', price_pence: 299, stock_quantity: 85, unit: 'bag', is_vegan: true, is_vegetarian: true, is_gluten_free: true, image_url: 'https://images.unsplash.com/photo-1536816579748-4ecb3f03d72a?w=400&h=400&fit=crop' },
    { name: 'Chocolate Chip Cookies 300g', slug: 'chocolate-chip-cookies-300g', short_description: 'Chunky choc chip cookies', description: 'Crunchy cookies loaded with chocolate chips.', price_pence: 199, stock_quantity: 100, unit: 'pack', is_vegetarian: true, image_url: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=400&h=400&fit=crop' },
    { name: 'Digestive Biscuits 400g', slug: 'digestive-biscuits-400g', short_description: 'Classic digestives', description: 'Traditional British digestive biscuits. Perfect with tea.', price_pence: 149, stock_quantity: 130, unit: 'pack', is_vegetarian: true, image_url: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=400&h=400&fit=crop' },
    { name: 'Popcorn Sweet & Salted 100g', slug: 'popcorn-sweet-salted-100g', short_description: 'Sweet and salty popcorn', description: 'Light, crunchy popcorn with the perfect sweet and salty balance.', price_pence: 149, stock_quantity: 110, unit: 'bag', is_vegan: true, is_vegetarian: true, is_gluten_free: true, image_url: 'https://images.unsplash.com/photo-1585238342070-61e1e768b1ff?w=400&h=400&fit=crop' },
    { name: 'Vanilla Ice Cream 900ml', slug: 'vanilla-ice-cream-900ml', short_description: 'Creamy vanilla ice cream', description: 'Rich, creamy vanilla ice cream made with real vanilla.', price_pence: 349, stock_quantity: 60, unit: 'tub', is_vegetarian: true, is_gluten_free: true, image_url: 'https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?w=400&h=400&fit=crop' },
    { name: 'Chocolate Ice Cream 900ml', slug: 'chocolate-ice-cream-900ml', short_description: 'Belgian chocolate ice cream', description: 'Indulgent chocolate ice cream made with Belgian chocolate.', price_pence: 349, stock_quantity: 55, unit: 'tub', is_vegetarian: true, is_gluten_free: true, image_url: 'https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?w=400&h=400&fit=crop' },
    { name: 'Frozen Garden Peas 900g', slug: 'frozen-garden-peas-900g', short_description: 'Sweet garden peas', description: 'Frozen at peak freshness for the sweetest taste.', price_pence: 179, stock_quantity: 90, unit: 'bag', is_vegan: true, is_vegetarian: true, is_gluten_free: true, image_url: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400&h=400&fit=crop' },
    { name: 'Frozen Chips 1.5kg', slug: 'frozen-chips-1-5kg', short_description: 'Crispy oven chips', description: 'Golden oven chips, crispy outside and fluffy inside.', price_pence: 279, stock_quantity: 80, unit: 'bag', is_vegan: true, is_vegetarian: true, is_gluten_free: true, image_url: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400&h=400&fit=crop' },
    { name: 'Frozen Pizza Margherita', slug: 'frozen-pizza-margherita', short_description: 'Classic margherita pizza', description: 'Stone-baked pizza with tomato sauce and mozzarella.', price_pence: 349, stock_quantity: 70, unit: 'each', is_vegetarian: true, image_url: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&h=400&fit=crop' },
    { name: 'Fish Fingers 10 Pack', slug: 'fish-fingers-10-pack', short_description: 'Crispy cod fish fingers', description: 'Golden, crispy fish fingers made with 100% cod fillet.', price_pence: 299, stock_quantity: 85, unit: 'box', image_url: 'https://images.unsplash.com/photo-1510130387422-82bed34b37e9?w=400&h=400&fit=crop' },
    { name: 'Frozen Berries Mix 500g', slug: 'frozen-berries-mix-500g', short_description: 'Mixed frozen berries', description: 'Strawberries, raspberries, and blueberries. Perfect for smoothies.', price_pence: 349, stock_quantity: 75, unit: 'bag', is_vegan: true, is_vegetarian: true, is_gluten_free: true, image_url: 'https://images.unsplash.com/photo-1498557850523-fd3d118b962e?w=400&h=400&fit=crop' },
    { name: 'Almond Milk 1L', slug: 'almond-milk-1l', short_description: 'Unsweetened almond milk', description: 'Creamy plant-based milk made from almonds. Dairy-free alternative.', price_pence: 189, stock_quantity: 100, unit: 'carton', is_vegan: true, is_vegetarian: true, is_gluten_free: true, image_url: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?w=400&h=400&fit=crop' },
    { name: 'Oat Milk 1L', slug: 'oat-milk-1l', short_description: 'Barista oat milk', description: 'Creamy oat milk that froths perfectly. Great in coffee.', price_pence: 199, stock_quantity: 95, unit: 'carton', is_vegan: true, is_vegetarian: true, image_url: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?w=400&h=400&fit=crop' },
    { name: 'Hummus 200g', slug: 'hummus-200g', short_description: 'Classic chickpea hummus', description: 'Smooth, creamy hummus with tahini and lemon. Perfect with pitta.', price_pence: 179, stock_quantity: 90, unit: 'pot', is_vegan: true, is_vegetarian: true, is_gluten_free: true, image_url: 'https://images.unsplash.com/photo-1515543904823-6701e98e4d6e?w=400&h=400&fit=crop' },
    { name: 'Guacamole 170g', slug: 'guacamole-170g', short_description: 'Fresh avocado dip', description: 'Chunky guacamole made with ripe avocados, lime and coriander.', price_pence: 229, stock_quantity: 70, unit: 'pot', is_vegan: true, is_vegetarian: true, is_gluten_free: true, image_url: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=400&h=400&fit=crop' },
    { name: 'Tortilla Chips 200g', slug: 'tortilla-chips-200g', short_description: 'Lightly salted tortillas', description: 'Crunchy corn tortilla chips. Perfect with salsa and guacamole.', price_pence: 169, stock_quantity: 110, unit: 'bag', is_vegan: true, is_vegetarian: true, is_gluten_free: true, image_url: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=400&h=400&fit=crop' },
  ],
]

// POST - Add products by batch number
export async function POST(request: NextRequest) {
  const supabaseAdmin = getSupabaseAdmin()

  const { searchParams } = new URL(request.url)
  const batchParam = searchParams.get('batch')
  const batch = batchParam ? parseInt(batchParam) : 1

  if (batch < 1 || batch > 5) {
    return NextResponse.json({ error: 'Batch must be between 1 and 5' }, { status: 400 })
  }

  const products = allProducts[batch - 1]

  try {
    // Add default values to each product
    const productsToInsert = products.map(p => {
      const product = p as Record<string, unknown>
      return {
        ...p,
        sku: `SKU-${p.slug.toUpperCase().slice(0, 10)}-${Math.random().toString(36).slice(2, 6).toUpperCase()}`,
        track_inventory: true,
        low_stock_threshold: 10,
        is_active: true,
        is_vegan: product.is_vegan || false,
        is_vegetarian: product.is_vegetarian || false,
        is_gluten_free: product.is_gluten_free || false,
        is_organic: product.is_organic || false,
        is_featured: product.is_featured || false,
      }
    })

    const { data, error } = await supabaseAdmin
      .from('products')
      .insert(productsToInsert)
      .select()

    if (error) {
      console.error('Insert error:', error)
      return NextResponse.json({ error: error.message }, { status: 500 })
    }

    return NextResponse.json({
      message: `Batch ${batch} added successfully`,
      batch,
      added: data?.length || 0,
      products: data?.map(p => p.name)
    })
  } catch (error) {
    console.error('Error:', error)
    return NextResponse.json({ error: 'Failed to add products' }, { status: 500 })
  }
}

// GET - Get batch info
export async function GET() {
  return NextResponse.json({
    message: 'Seed Products API',
    batches: [
      { batch: 1, name: 'Fruits & Vegetables', count: 20 },
      { batch: 2, name: 'Dairy, Eggs & Bakery', count: 20 },
      { batch: 3, name: 'Meat & Fish', count: 20 },
      { batch: 4, name: 'Pantry & Beverages', count: 20 },
      { batch: 5, name: 'Snacks, Frozen & More', count: 20 },
    ],
    usage: 'POST /api/admin/seed-products?batch=1 to add batch 1'
  })
}
